### PR TITLE
Adding CS:S Support

### PR DESCRIPTION
**Pull request by data-bomb**
- Adds two forwards SJD_DoorsOpened and SJD_DoorsClosed for other plugins
- Forcing prop_dynamic and disabling of glowing for CS:S Support

### CODE REVIEW

**Comment by data-bomb** [comment]
Hmm the forward seemed to be the right spot but it's only working when I do the following:
!sjd -> Doors -> Remove current door -> Re-add Jail Door
Then opening or closing the doors causes the forward to trigger.  I have not isolated the bug yet.

**Comment by data-bomb** [comment]
https://github.com/Kailo97/smartjaildoors/pull/2 fixes the issue where forward was only working in strange situations

**Comment by Kailo97** [comment]
- Forward must have void return type.
- I think need remove "glow" cvars if not CS:GO game.

P.S. I uploaded some changes from local (This may to do conflicts).

**Comment by data-bomb** [comment]
Agreed, will close these and re-submit for your review.

**Comment by TiBarification** [comment]
@data-bomb , @Kailo97 ,nice to see that the plugin is updated.
ASAP i will do update to my **[JWP] Doors** module.

**Pull request closed without merging**
